[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#a0a0a0"
blue = "#0451a5"
cyan = "#0598bc"
green = "#1e8a29"
magenta = "#bc05bc"
red = "#cd3131"
white = "#1e1e1e"
yellow = "#b5a000"

[colors.normal]
black = "#282c34"
blue = "#0451a5"
cyan = "#0598bc"
green = "#1e8a29"
magenta = "#bc05bc"
red = "#cd3131"
white = "#3b3b3b"
yellow = "#b5a000"

[colors.primary]
background = "#ffffff"
foreground = "#3b3b3b"

[font]
size = 18

[font.bold]
family = "Monaco Nerd Font"
style = "Regular"

[font.italic]
family = "Monaco Nerd Font"
style = "Regular"

[font.normal]
family = "Monaco Nerd Font"
style = "Regular"

# [font.offset]
# x = 0
# y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "J"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;2P"
key = "B"
mods = "Command|Option"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002/"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002/"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\\"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "{"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "}"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"
mode = "AppKeypad"

[[keyboard.bindings]]
chars = "\u001B[P"
key = "Delete"
mode = "~AppKeypad"

[scrolling]
history = 0

[window]
decorations = "Transparent"
dynamic_title = true
startup_mode = "Maximized"
